 
stateStores:
- kind: GitStateStore
  name: default
  namespace: default
    # The branch to write to: optional, defaults to main
  branch: main
  # Required
  secretRef:
    # The name and namespace of the secret to use to authenticate: required
    name: labs-credentials
  path: "destinations"
  # The address of the git repository. If auth method is basic auth, use `http`/`https` format: required
  # if your using ssh auth then ensure its of the format git@github.com:<org>/<repo>.git
  url: ${git_url}

destinations:
- name: worker-1
  namespace: default
  labels:
    environment: dev
  path: "dev"
  stateStoreRef:
    name: default
    kind: GitStateStore

- name: platform-cluster
  namespace: default
  labels:
    environment: dev
  path: ""
  stateStoreRef:
    name: default
    kind: GitStateStore

additionalResources:
- apiVersion: v1
  kind: Secret
  metadata:
    name: labs-credentials
    namespace: default
  type: Opaque
  data:
    username: ${git_username}
    password: ${git_password}